name: Stock Service CI

on:
  push:
    paths:
      - 'stockservice-go/**'
  pull_request:
    paths:
      - 'stockservice-go/**'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.2

      - name: Verify Go Version
        run: go version

      - name: Install Dependencies
        run: go mod tidy
        working-directory: stockservice-go

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Run Linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...
        working-directory: stockservice-go

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Run Unit Tests
        run: go test -v ./... -coverprofile=coverage.out
        working-directory: stockservice-go

      - name: Check Coverage
        run: go tool cover -func=coverage.out
        working-directory: stockservice-go

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Compile
        run: go build ./...
        working-directory: stockservice-go
