name: Stock Service CI

on:
  push:
    paths:
      - 'stockservice-go/**'
  pull_request:
    paths:
      - 'stockservice-go/**'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install Dependencies
        run: go mod tidy

  compile:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build Project
        run: go build -o ./bin/stockservice ./...

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Install Linter
        run: go install golang.org/x/lint/golint@latest

      - name: Run Linter
        run: golint ./...

  test:
    runs-on: ubuntu-latest
    needs: [install-dependencies, compile]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Run Tests
        run: go test -v ./... -coverprofile=coverage.out

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Check Coverage
        run: go tool cover -func=coverage.out
